start: (contexto_def | mandante_def | booleano_def | tetrada_def | fractal_def | contract_def | invariant_def | asiento_declarado_def)*

contexto_def: "CONTEXTO" ":" assignment+
mandante_def: "MANDANTE" ":" assignment+
booleano_def: "BOOLEANO" ":" booleano_item+
booleano_item: NAME "=" value
tetrada_def: "TETRADA" ":" tetrada_item+
tetrada_item: NAME "=" value

fractal_def: "FRACTAL" NAME "DOMINIO" "CONTABLE" ":" rule+
rule: "REGLA" NAME ":" condition "ENTONCES" action+

contract_def: CONTRATO NAME OBJETO ":" NAME [PRE ":" expr] [POST ":" expr] INVARIANTE ":" NAME+ ELEMENTO ":" NAME+ [EVIDENCIA ":" NAME+]
invariant_def: INVARIANTE NAME OBJETO ":" NAME EXPRESION ":" expr DOMINIO ":" NAME SATISFACCION ":" expr VERIFICACION ":" NAME EVIDENCIA ":" NAME+
asiento_declarado_def: ASIENTO_DECLARADO NAME ":" NAME+

CONTRATO: "CONTRATO"
OBJETO: "OBJETO"
PRE: "PRE"
POST: "POST"
INVARIANTE: "INVARIANTE"
ELEMENTO: "ELEMENTO"
EVIDENCIA: "EVIDENCIA"
EXPRESION: "EXPRESION"
DOMINIO: "DOMINIO"
SATISFACCION: "SATISFACCION"
VERIFICACION: "VERIFICACION"
ASIENTO_DECLARADO: "ASIENTO_DECLARADO"

condition: "SI" expr ((AND_OP | OR_OP) expr)*
?expr: comparison
?comparison: arith (COMPOP arith)?
?arith: term (ADDOP term)*
?term: factor (MULOP factor)*
?factor: NUMBER | STRING | BOOLEAN | NAME | list_value | "(" arith ")" | "-" factor

list_value: "[" [value ("," value)*] "]"
value: NUMBER | STRING | BOOLEAN | NAME | list_value

action: assignment | generate
generate: "GENERAR" "CONSECUENCIA" "(" param_list ")"
param_list: param ("," param)*
param: NAME "=" arith

assignment: NAME "=" arith

AND_OP: "Y"
OR_OP:  "O"
COMPOP: "==" | "!=" | ">=" | "<=" | ">" | "<"
ADDOP: "+" | "-"
MULOP: "*" | "/"

NAME: /[A-Za-z_][A-Za-z0-9_]*/
NUMBER: /\d+(\.\d+)?/
STRING: /"[^"]*"/
BOOLEAN: "VERDADERO" | "FALSO"

%import common.WS
%ignore WS
%ignore /#.*/
